[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font = "monospace"

[server]
port = 8501
enableStaticServing = true
sslCertFile = ''
sslKeyFile = ''

